const express = require('express')
const router = express.Router()
const indexController = require('../controllers/index')
const authController = require('../controllers/auth') 
const { ensureAuth, ensureGuest } = require('../middleware/auth')

router.get('/', indexController.getIndex)
router.get('/login', authController.getLogin)
router.post('/login', authController.postLogin)
router.get('/logout', authController.logout)
router.get('/signup', authController.getSignup)
router.post('/signup', authController.postSignup)
// router.get('/reset', authController.resetPassword)
// router.post('/reset', authController.postResetPassword)
module.exports = router